name: "🔄 Check'n'Merge Upstream"

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:
    inputs: {}

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.SURF_BOT_PAT }}
      - uses: fopina/upstream-to-pr@v1
        with:
          token: ${{ secrets.SURF_BOT_PAT }}
          upstream-repository: https://github.com/projectdiscovery/httpx
          upstream-tag: 'v\d+\.\d+\.\d+'
