name: Fetch and merge upstream repository
on:
  schedule:
    - cron:  '0 7 * * *'
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git pull --unshallow  
          git remote add upstream https://github.com/projectdiscovery/httpx.git
          git fetch upstream

          git checkout -b new_branch/x origin/new_branch/x
          git merge --no-edit upstream/new_branch/x
          git push origin new_branch/x

          git checkout master
          git merge --no-edit upstream/master
          git push origin master